### ISSUE TITLE
Question about Project Euler Problem 4

### ISSUE THREAD

**Issue by asarkar** [adamdrake/adamdrake.github.io#1]
I came across your blog post [An Unreasonably Deep Dive Into Project Euler Problem 4](https://adamdrake.com/an-unreasonably-deep-dive-into-project-euler-problem-4.html). Thanks for the write-up. Since your blog doesn't have a comment section, I'm asking my question here, hope that's ok.

The reasoning behind v4 of the algorithm says "Note that the number is probably 6 digits". This seems hand-wavy, since the product of two 3-digit numbers doesn't necessarily have to be 6-digits, and the use of the word "probably" indicates that you've your own doubts, still, this fact is exploited to improve the algorithm.

What are your thoughts on this?

**Comment by adamdrake** [comment]
Thank you for your comment.  You are correct that the wording is hand-wavy, and it took me some time to remember why I wrote it that way.

Recall we are searching for the *largest* palindromic number that is the product of two 3-digit numbers.  Call this set of palindromic numbers _P_.  Consider the set _S_ of numbers that are the product of two 3-digit numbers.  The largest element of _S_ is the product of the largest 3-digit numbers, 999 * 999 = 998001.  The set of palindromic numbers _P_ must be a subset of _S_.  Therefore, we know that the upper bound of the search space is a 6-digit number.

With that in mind, we need only show the existence of a 6-digit number in _P_ to conclude we can ignore the space of 5-digit numbers.  In other words, if there exists any 6-digit palindromic number _x_ that is the product of two 3-digit numbers _p_ and _q_, then we do not need to search any of the 5-digit space because _x_ is either the largest palindromic number (and is six digits long) or there is a larger palindromic number that will also be six digits long.

Since we know such a number _x_ exists, we can ignore the 5-digit search space because we have demonstrated (a) there is a 6-digit palindromic number _x_ and (b) any larger palindromic numbers that are the product of two 3-digit numbers would also have six digits.

Thank you for the clarification request, and I'll consider editing the post and code comments to provide additional detail on the reasoning.

Wishing you a Happy New Year!

**Comment by asarkar** [comment]
Makes sense now. The smallest product of two 3-digit numbers is `100x100=10000`, but since we are looking for the largest product, we can ignore the 5-digit products. This is the part that I missed during my reading of the article.
Thanks for the clarification, and wish you a happy new year too.
